# Generated by Django 4.0 on 2022-02-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
